// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package controllerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// GetPendingBoot returns boot info for a MAC with pending provision
	GetPendingBoot(ctx context.Context, in *GetPendingBootRequest, opts ...grpc.CallOption) (*GetPendingBootResponse, error)
	// MarkBootStarted marks a provision as InProgress
	MarkBootStarted(ctx context.Context, in *MarkBootStartedRequest, opts ...grpc.CallOption) (*MarkBootStartedResponse, error)
	// MarkBootCompleted marks a provision as Complete
	MarkBootCompleted(ctx context.Context, in *MarkBootCompletedRequest, opts ...grpc.CallOption) (*MarkBootCompletedResponse, error)
	// GetConfigMapValue retrieves a value from a ConfigMap by key
	GetConfigMapValue(ctx context.Context, in *GetConfigMapValueRequest, opts ...grpc.CallOption) (*GetConfigMapValueResponse, error)
	// GetBootTarget retrieves a BootTarget by name
	GetBootTarget(ctx context.Context, in *GetBootTargetRequest, opts ...grpc.CallOption) (*GetBootTargetResponse, error)
	// GetResponseTemplate retrieves a ResponseTemplate by name
	GetResponseTemplate(ctx context.Context, in *GetResponseTemplateRequest, opts ...grpc.CallOption) (*GetResponseTemplateResponse, error)
	// GetProvision retrieves a Provision by name
	GetProvision(ctx context.Context, in *GetProvisionRequest, opts ...grpc.CallOption) (*GetProvisionResponse, error)
	// GetConfigMaps retrieves and merges data from multiple ConfigMaps
	GetConfigMaps(ctx context.Context, in *GetConfigMapsRequest, opts ...grpc.CallOption) (*GetConfigMapsResponse, error)
	// GetSecrets retrieves and merges data from multiple Secrets
	GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) GetPendingBoot(ctx context.Context, in *GetPendingBootRequest, opts ...grpc.CallOption) (*GetPendingBootResponse, error) {
	out := new(GetPendingBootResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetPendingBoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) MarkBootStarted(ctx context.Context, in *MarkBootStartedRequest, opts ...grpc.CallOption) (*MarkBootStartedResponse, error) {
	out := new(MarkBootStartedResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/MarkBootStarted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) MarkBootCompleted(ctx context.Context, in *MarkBootCompletedRequest, opts ...grpc.CallOption) (*MarkBootCompletedResponse, error) {
	out := new(MarkBootCompletedResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/MarkBootCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetConfigMapValue(ctx context.Context, in *GetConfigMapValueRequest, opts ...grpc.CallOption) (*GetConfigMapValueResponse, error) {
	out := new(GetConfigMapValueResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetConfigMapValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetBootTarget(ctx context.Context, in *GetBootTargetRequest, opts ...grpc.CallOption) (*GetBootTargetResponse, error) {
	out := new(GetBootTargetResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetBootTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetResponseTemplate(ctx context.Context, in *GetResponseTemplateRequest, opts ...grpc.CallOption) (*GetResponseTemplateResponse, error) {
	out := new(GetResponseTemplateResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetResponseTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetProvision(ctx context.Context, in *GetProvisionRequest, opts ...grpc.CallOption) (*GetProvisionResponse, error) {
	out := new(GetProvisionResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetProvision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetConfigMaps(ctx context.Context, in *GetConfigMapsRequest, opts ...grpc.CallOption) (*GetConfigMapsResponse, error) {
	out := new(GetConfigMapsResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetConfigMaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error) {
	out := new(GetSecretsResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetSecrets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility
type ControllerServiceServer interface {
	// GetPendingBoot returns boot info for a MAC with pending provision
	GetPendingBoot(context.Context, *GetPendingBootRequest) (*GetPendingBootResponse, error)
	// MarkBootStarted marks a provision as InProgress
	MarkBootStarted(context.Context, *MarkBootStartedRequest) (*MarkBootStartedResponse, error)
	// MarkBootCompleted marks a provision as Complete
	MarkBootCompleted(context.Context, *MarkBootCompletedRequest) (*MarkBootCompletedResponse, error)
	// GetConfigMapValue retrieves a value from a ConfigMap by key
	GetConfigMapValue(context.Context, *GetConfigMapValueRequest) (*GetConfigMapValueResponse, error)
	// GetBootTarget retrieves a BootTarget by name
	GetBootTarget(context.Context, *GetBootTargetRequest) (*GetBootTargetResponse, error)
	// GetResponseTemplate retrieves a ResponseTemplate by name
	GetResponseTemplate(context.Context, *GetResponseTemplateRequest) (*GetResponseTemplateResponse, error)
	// GetProvision retrieves a Provision by name
	GetProvision(context.Context, *GetProvisionRequest) (*GetProvisionResponse, error)
	// GetConfigMaps retrieves and merges data from multiple ConfigMaps
	GetConfigMaps(context.Context, *GetConfigMapsRequest) (*GetConfigMapsResponse, error)
	// GetSecrets retrieves and merges data from multiple Secrets
	GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServiceServer struct {
}

func (UnimplementedControllerServiceServer) GetPendingBoot(context.Context, *GetPendingBootRequest) (*GetPendingBootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingBoot not implemented")
}
func (UnimplementedControllerServiceServer) MarkBootStarted(context.Context, *MarkBootStartedRequest) (*MarkBootStartedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkBootStarted not implemented")
}
func (UnimplementedControllerServiceServer) MarkBootCompleted(context.Context, *MarkBootCompletedRequest) (*MarkBootCompletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkBootCompleted not implemented")
}
func (UnimplementedControllerServiceServer) GetConfigMapValue(context.Context, *GetConfigMapValueRequest) (*GetConfigMapValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigMapValue not implemented")
}
func (UnimplementedControllerServiceServer) GetBootTarget(context.Context, *GetBootTargetRequest) (*GetBootTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBootTarget not implemented")
}
func (UnimplementedControllerServiceServer) GetResponseTemplate(context.Context, *GetResponseTemplateRequest) (*GetResponseTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResponseTemplate not implemented")
}
func (UnimplementedControllerServiceServer) GetProvision(context.Context, *GetProvisionRequest) (*GetProvisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvision not implemented")
}
func (UnimplementedControllerServiceServer) GetConfigMaps(context.Context, *GetConfigMapsRequest) (*GetConfigMapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigMaps not implemented")
}
func (UnimplementedControllerServiceServer) GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecrets not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s *grpc.Server, srv ControllerServiceServer) {
	s.RegisterService(&_ControllerService_serviceDesc, srv)
}

func _ControllerService_GetPendingBoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingBootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetPendingBoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetPendingBoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetPendingBoot(ctx, req.(*GetPendingBootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_MarkBootStarted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBootStartedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).MarkBootStarted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/MarkBootStarted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).MarkBootStarted(ctx, req.(*MarkBootStartedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_MarkBootCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBootCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).MarkBootCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/MarkBootCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).MarkBootCompleted(ctx, req.(*MarkBootCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetConfigMapValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigMapValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetConfigMapValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetConfigMapValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetConfigMapValue(ctx, req.(*GetConfigMapValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetBootTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetBootTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetBootTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetBootTarget(ctx, req.(*GetBootTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetResponseTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponseTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetResponseTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetResponseTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetResponseTemplate(ctx, req.(*GetResponseTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetProvision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetProvision(ctx, req.(*GetProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetConfigMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetConfigMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetConfigMaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetConfigMaps(ctx, req.(*GetConfigMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetSecrets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetSecrets(ctx, req.(*GetSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "isoboot.controller.v1.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingBoot",
			Handler:    _ControllerService_GetPendingBoot_Handler,
		},
		{
			MethodName: "MarkBootStarted",
			Handler:    _ControllerService_MarkBootStarted_Handler,
		},
		{
			MethodName: "MarkBootCompleted",
			Handler:    _ControllerService_MarkBootCompleted_Handler,
		},
		{
			MethodName: "GetConfigMapValue",
			Handler:    _ControllerService_GetConfigMapValue_Handler,
		},
		{
			MethodName: "GetBootTarget",
			Handler:    _ControllerService_GetBootTarget_Handler,
		},
		{
			MethodName: "GetResponseTemplate",
			Handler:    _ControllerService_GetResponseTemplate_Handler,
		},
		{
			MethodName: "GetProvision",
			Handler:    _ControllerService_GetProvision_Handler,
		},
		{
			MethodName: "GetConfigMaps",
			Handler:    _ControllerService_GetConfigMaps_Handler,
		},
		{
			MethodName: "GetSecrets",
			Handler:    _ControllerService_GetSecrets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/controller.proto",
}
