// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package controllerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// GetPendingBoot returns boot info for a MAC with pending deploy
	GetPendingBoot(ctx context.Context, in *GetPendingBootRequest, opts ...grpc.CallOption) (*GetPendingBootResponse, error)
	// MarkBootStarted marks a deploy as InProgress
	MarkBootStarted(ctx context.Context, in *MarkBootStartedRequest, opts ...grpc.CallOption) (*MarkBootStartedResponse, error)
	// MarkBootCompleted marks a deploy as Completed
	MarkBootCompleted(ctx context.Context, in *MarkBootCompletedRequest, opts ...grpc.CallOption) (*MarkBootCompletedResponse, error)
	// GetTemplate retrieves a boot template
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) GetPendingBoot(ctx context.Context, in *GetPendingBootRequest, opts ...grpc.CallOption) (*GetPendingBootResponse, error) {
	out := new(GetPendingBootResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetPendingBoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) MarkBootStarted(ctx context.Context, in *MarkBootStartedRequest, opts ...grpc.CallOption) (*MarkBootStartedResponse, error) {
	out := new(MarkBootStartedResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/MarkBootStarted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) MarkBootCompleted(ctx context.Context, in *MarkBootCompletedRequest, opts ...grpc.CallOption) (*MarkBootCompletedResponse, error) {
	out := new(MarkBootCompletedResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/MarkBootCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error) {
	out := new(GetTemplateResponse)
	err := c.cc.Invoke(ctx, "/isoboot.controller.v1.ControllerService/GetTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility
type ControllerServiceServer interface {
	// GetPendingBoot returns boot info for a MAC with pending deploy
	GetPendingBoot(context.Context, *GetPendingBootRequest) (*GetPendingBootResponse, error)
	// MarkBootStarted marks a deploy as InProgress
	MarkBootStarted(context.Context, *MarkBootStartedRequest) (*MarkBootStartedResponse, error)
	// MarkBootCompleted marks a deploy as Completed
	MarkBootCompleted(context.Context, *MarkBootCompletedRequest) (*MarkBootCompletedResponse, error)
	// GetTemplate retrieves a boot template
	GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServiceServer struct {
}

func (UnimplementedControllerServiceServer) GetPendingBoot(context.Context, *GetPendingBootRequest) (*GetPendingBootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingBoot not implemented")
}
func (UnimplementedControllerServiceServer) MarkBootStarted(context.Context, *MarkBootStartedRequest) (*MarkBootStartedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkBootStarted not implemented")
}
func (UnimplementedControllerServiceServer) MarkBootCompleted(context.Context, *MarkBootCompletedRequest) (*MarkBootCompletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkBootCompleted not implemented")
}
func (UnimplementedControllerServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s *grpc.Server, srv ControllerServiceServer) {
	s.RegisterService(&_ControllerService_serviceDesc, srv)
}

func _ControllerService_GetPendingBoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingBootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetPendingBoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetPendingBoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetPendingBoot(ctx, req.(*GetPendingBootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_MarkBootStarted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBootStartedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).MarkBootStarted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/MarkBootStarted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).MarkBootStarted(ctx, req.(*MarkBootStartedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_MarkBootCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBootCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).MarkBootCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/MarkBootCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).MarkBootCompleted(ctx, req.(*MarkBootCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isoboot.controller.v1.ControllerService/GetTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "isoboot.controller.v1.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingBoot",
			Handler:    _ControllerService_GetPendingBoot_Handler,
		},
		{
			MethodName: "MarkBootStarted",
			Handler:    _ControllerService_MarkBootStarted_Handler,
		},
		{
			MethodName: "MarkBootCompleted",
			Handler:    _ControllerService_MarkBootCompleted_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _ControllerService_GetTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
