apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  labels:
    app.kubernetes.io/name: isoboot
    app.kubernetes.io/managed-by: kustomize
  name: rocky-9-kernel
spec:
  url: https://download.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/images/pxeboot/vmlinuz
  sha256: "0000000000000000000000000000000000000000000000000000000000000000"
