apiVersion: isoboot.github.io/v1alpha1
kind: Provision
metadata:
  labels:
    app.kubernetes.io/name: isoboot
    app.kubernetes.io/managed-by: kustomize
  name: provision-sample
spec:
  machineRef: machine-sample
  bootConfigRef: rocky-9
  provisionAutomationRef: provisionautomation-sample
