//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootSource) DeepCopyInto(out *BootSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootSource.
func (in *BootSource) DeepCopy() *BootSource {
	if in == nil {
		return nil
	}
	out := new(BootSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootSourceList) DeepCopyInto(out *BootSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootSourceList.
func (in *BootSourceList) DeepCopy() *BootSourceList {
	if in == nil {
		return nil
	}
	out := new(BootSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootSourceSpec) DeepCopyInto(out *BootSourceSpec) {
	*out = *in
	if in.Kernel != nil {
		in, out := &in.Kernel, &out.Kernel
		*out = new(DownloadableResource)
		(*in).DeepCopyInto(*out)
	}
	if in.Initrd != nil {
		in, out := &in.Initrd, &out.Initrd
		*out = new(DownloadableResource)
		(*in).DeepCopyInto(*out)
	}
	if in.ISO != nil {
		in, out := &in.ISO, &out.ISO
		*out = new(ISOSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(DownloadableResource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootSourceSpec.
func (in *BootSourceSpec) DeepCopy() *BootSourceSpec {
	if in == nil {
		return nil
	}
	out := new(BootSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootSourceStatus) DeepCopyInto(out *BootSourceStatus) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]ResourceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootSourceStatus.
func (in *BootSourceStatus) DeepCopy() *BootSourceStatus {
	if in == nil {
		return nil
	}
	out := new(BootSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadableResource) DeepCopyInto(out *DownloadableResource) {
	*out = *in
	if in.ShasumURL != nil {
		in, out := &in.ShasumURL, &out.ShasumURL
		*out = new(string)
		**out = **in
	}
	if in.Shasum != nil {
		in, out := &in.Shasum, &out.Shasum
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadableResource.
func (in *DownloadableResource) DeepCopy() *DownloadableResource {
	if in == nil {
		return nil
	}
	out := new(DownloadableResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOSource) DeepCopyInto(out *ISOSource) {
	*out = *in
	in.DownloadableResource.DeepCopyInto(&out.DownloadableResource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOSource.
func (in *ISOSource) DeepCopy() *ISOSource {
	if in == nil {
		return nil
	}
	out := new(ISOSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}
