//go:build !ignore_autogenerated

// Hand-written deepcopy functions for CRD types.
// Equivalent to controller-gen object output.

package k8s

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- Machine ---

func (in *Machine) DeepCopyInto(out *Machine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *Machine) DeepCopy() *Machine {
	if in == nil {
		return nil
	}
	out := new(Machine)
	in.DeepCopyInto(out)
	return out
}

func (in *Machine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MachineList) DeepCopyInto(out *MachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Machine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MachineList) DeepCopy() *MachineList {
	if in == nil {
		return nil
	}
	out := new(MachineList)
	in.DeepCopyInto(out)
	return out
}

func (in *MachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- Provision ---

func (in *ProvisionSpec) DeepCopyInto(out *ProvisionSpec) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ProvisionStatus) DeepCopyInto(out *ProvisionStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

func (in *Provision) DeepCopyInto(out *Provision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Provision) DeepCopy() *Provision {
	if in == nil {
		return nil
	}
	out := new(Provision)
	in.DeepCopyInto(out)
	return out
}

func (in *Provision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProvisionList) DeepCopyInto(out *ProvisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProvisionList) DeepCopy() *ProvisionList {
	if in == nil {
		return nil
	}
	out := new(ProvisionList)
	in.DeepCopyInto(out)
	return out
}

func (in *ProvisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- BootMedia ---

func (in *BootMediaFileRef) DeepCopyInto(out *BootMediaFileRef) {
	*out = *in
}

func (in *BootMediaFileRef) DeepCopy() *BootMediaFileRef {
	if in == nil {
		return nil
	}
	out := new(BootMediaFileRef)
	in.DeepCopyInto(out)
	return out
}

func (in *BootMediaISO) DeepCopyInto(out *BootMediaISO) {
	*out = *in
}

func (in *BootMediaISO) DeepCopy() *BootMediaISO {
	if in == nil {
		return nil
	}
	out := new(BootMediaISO)
	in.DeepCopyInto(out)
	return out
}

func (in *BootMediaSpec) DeepCopyInto(out *BootMediaSpec) {
	*out = *in
	if in.Kernel != nil {
		in, out := &in.Kernel, &out.Kernel
		*out = new(BootMediaFileRef)
		**out = **in
	}
	if in.Initrd != nil {
		in, out := &in.Initrd, &out.Initrd
		*out = new(BootMediaFileRef)
		**out = **in
	}
	if in.ISO != nil {
		in, out := &in.ISO, &out.ISO
		*out = new(BootMediaISO)
		**out = **in
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(BootMediaFileRef)
		**out = **in
	}
}

func (in *FileStatus) DeepCopyInto(out *FileStatus) {
	*out = *in
}

func (in *FileStatus) DeepCopy() *FileStatus {
	if in == nil {
		return nil
	}
	out := new(FileStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BootMediaStatus) DeepCopyInto(out *BootMediaStatus) {
	*out = *in
	if in.Kernel != nil {
		in, out := &in.Kernel, &out.Kernel
		*out = new(FileStatus)
		**out = **in
	}
	if in.Initrd != nil {
		in, out := &in.Initrd, &out.Initrd
		*out = new(FileStatus)
		**out = **in
	}
	if in.ISO != nil {
		in, out := &in.ISO, &out.ISO
		*out = new(FileStatus)
		**out = **in
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(FileStatus)
		**out = **in
	}
	if in.FirmwareInitrd != nil {
		in, out := &in.FirmwareInitrd, &out.FirmwareInitrd
		*out = new(FileStatus)
		**out = **in
	}
}

func (in *BootMedia) DeepCopyInto(out *BootMedia) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BootMedia) DeepCopy() *BootMedia {
	if in == nil {
		return nil
	}
	out := new(BootMedia)
	in.DeepCopyInto(out)
	return out
}

func (in *BootMedia) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BootMediaList) DeepCopyInto(out *BootMediaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootMedia, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BootMediaList) DeepCopy() *BootMediaList {
	if in == nil {
		return nil
	}
	out := new(BootMediaList)
	in.DeepCopyInto(out)
	return out
}

func (in *BootMediaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- BootTarget ---

func (in *BootTargetSpec) DeepCopyInto(out *BootTargetSpec) {
	*out = *in
}

func (in *BootTarget) DeepCopyInto(out *BootTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *BootTarget) DeepCopy() *BootTarget {
	if in == nil {
		return nil
	}
	out := new(BootTarget)
	in.DeepCopyInto(out)
	return out
}

func (in *BootTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BootTargetList) DeepCopyInto(out *BootTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BootTargetList) DeepCopy() *BootTargetList {
	if in == nil {
		return nil
	}
	out := new(BootTargetList)
	in.DeepCopyInto(out)
	return out
}

func (in *BootTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- ResponseTemplate ---

func (in *ResponseTemplateSpec) DeepCopyInto(out *ResponseTemplateSpec) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ResponseTemplate) DeepCopyInto(out *ResponseTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *ResponseTemplate) DeepCopy() *ResponseTemplate {
	if in == nil {
		return nil
	}
	out := new(ResponseTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *ResponseTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ResponseTemplateList) DeepCopyInto(out *ResponseTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResponseTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ResponseTemplateList) DeepCopy() *ResponseTemplateList {
	if in == nil {
		return nil
	}
	out := new(ResponseTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *ResponseTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
