apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: alma-9.8-kernel
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://repo.almalinux.org/almalinux/9.8/BaseOS/x86_64/os/images/pxeboot/vmlinuz
  sha256: "6680128c01a4b27bc3760b4ea85b28be9ffefb719a4724adc45b8536a20c594a"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: alma-9.8-initrd
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://repo.almalinux.org/almalinux/9.8/BaseOS/x86_64/os/images/pxeboot/initrd.img
  sha256: "95850ddb10eea1ea8f837a429cb00168880feb41d80da0a3cbd3ae4622f146e2"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootConfig
metadata:
  name: alma-9.8
  labels:
    app.kubernetes.io/name: isoboot
spec:
  netboot:
    kernelRef: alma-9.8-kernel
    initrdRef: alma-9.8-initrd
  kernelArgs: "ip=dhcp {{if .ProxyURL}}inst.proxy={{.ProxyURL}} {{end}}inst.repo=http://repo.almalinux.org/almalinux/9.8/BaseOS/x86_64/os inst.ks={{.ProvisionAutomationBaseURL}}/ks.cfg"
