apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: alma-9.7-kernel
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://repo.almalinux.org/almalinux/9.7/BaseOS/x86_64/os/images/pxeboot/vmlinuz
  sha256: "60f569e466a6ef6f4db9f87a36bacf286e28f069bbd4bcc8f7097ed1a71a6000"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: alma-9.7-initrd
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://repo.almalinux.org/almalinux/9.7/BaseOS/x86_64/os/images/pxeboot/initrd.img
  sha256: "30224b8640420889afd1029de827fd00261603a4024c813228ffc11ab0b0ce76"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootConfig
metadata:
  name: alma-9.7
  labels:
    app.kubernetes.io/name: isoboot
spec:
  kernel:
    ref: alma-9.7-kernel
    args: "ip=dhcp {{if .ProxyURL}}inst.proxy={{.ProxyURL}} {{end}}inst.repo=http://repo.almalinux.org/almalinux/9.7/BaseOS/x86_64/os inst.ks={{.ProvisionAutomationBaseURL}}/ks.cfg"
  initrd:
    ref: alma-9.7-initrd
