apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: debian-13-kernel
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
  sha256: "e3b18c3f1700aee0b59e82c82fafbc6f63a138dd319103821899a0dc37b4db9e"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: debian-13-initrd
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
  sha256: "653b254a530529d544fe2d0420078cdd3e595cce32ed782187e7d69ffc959ad8"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootConfig
metadata:
  name: debian-13
  labels:
    app.kubernetes.io/name: isoboot
spec:
  kernel:
    ref: debian-13-kernel
    args: "console=ttyS0,115200 auto=true priority=critical {{if .ProxyURL}}mirror/http/proxy={{.ProxyURL}} {{end}}preseed/url={{.ProvisionAutomationBaseURL}}/preseed.cfg"
  initrd:
    ref: debian-13-initrd
