apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: rocky-8.10-kernel
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://download.rockylinux.org/pub/rocky/8.10/BaseOS/x86_64/os/images/pxeboot/vmlinuz
  sha256: "4df48703b86574bb20576b14f9c209e6149aabe6ad06ccb709131fee48b46fed"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootArtifact
metadata:
  name: rocky-8.10-initrd
  labels:
    app.kubernetes.io/name: isoboot
spec:
  url: https://download.rockylinux.org/pub/rocky/8.10/BaseOS/x86_64/os/images/pxeboot/initrd.img
  sha256: "3ced31fac810242419b93d74f32f7f55d6dd607d3b50b4c5663ad03be2fafa02"
---
apiVersion: isoboot.github.io/v1alpha1
kind: BootConfig
metadata:
  name: rocky-8.10
  labels:
    app.kubernetes.io/name: isoboot
spec:
  kernel:
    ref: rocky-8.10-kernel
    args: "ip=dhcp {{if .ProxyURL}}inst.proxy={{.ProxyURL}} {{end}}inst.repo=http://download.rockylinux.org/pub/rocky/8.10/BaseOS/x86_64/os inst.ks={{.ProvisionAutomationBaseURL}}/ks.cfg"
  initrd:
    ref: rocky-8.10-initrd
