name: Publish Helm Chart

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: v4.1.0
      - run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm package charts/isoboot --version $VERSION --app-version $VERSION
          helm push isoboot-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}
